data :
  data_dir: datasets
  category: iid
  image_size: 8
  batch_size: 32
  imput_channel : 1
  seed : 3


model:
  checkpoint_dir: checkpoints
  checkpoint_name: weights
  learning_rate: 3e-4
  weight_decay: 0.05
  epochs: 4000
  eta : 1
  trajectory_steps: 1000

  test_trajectory_steps: 200
  skip : 40

  beta_start : 0.0001
  beta_end : 0.02
  device: 'cpu'
  save_model: True
